// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VanadoProjekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309092014_MakeVrijemeZavrsetkaNullable")]
    partial class MakeVrijemeZavrsetkaNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kvar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int?>("StrojId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VrijemePocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VrijemeZavrsetka")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrojId");

                    b.ToTable("Kvarovi");
                });

            modelBuilder.Entity("Stroj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Strojevi");
                });

            modelBuilder.Entity("Kvar", b =>
                {
                    b.HasOne("Stroj", "Stroj")
                        .WithMany("Kvarovi")
                        .HasForeignKey("StrojId");

                    b.Navigation("Stroj");
                });

            modelBuilder.Entity("Stroj", b =>
                {
                    b.Navigation("Kvarovi");
                });
#pragma warning restore 612, 618
        }
    }
}
